//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BurgerPlusUC.ApplicationDate
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer_order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public customer_order()
        {
            this.order_item = new HashSet<order_item>();
        }
    
        public int order_id { get; set; }
        public string order_number { get; set; }
        public System.DateTime order_date { get; set; }
        public string customer_id { get; set; }
        public decimal total_amount { get; set; }
        public int user_id { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual user user { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order_item> order_item { get; set; }
    }
}
