//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BurgerPlusUC.ApplicationDate
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBBurgerPlusEntities1 : DbContext
    {
        public DBBurgerPlusEntities1()
            : base("name=DBBurgerPlusEntities1")
        {
        }

        private static DBBurgerPlusEntities1 _context;

        public static DBBurgerPlusEntities1 GetContext()
        {
            if (_context == null)
                _context = new DBBurgerPlusEntities1();
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<customer> customer { get; set; }
        public virtual DbSet<customer_order> customer_order { get; set; }
        public virtual DbSet<order_item> order_item { get; set; }
        public virtual DbSet<product> product { get; set; }
        public virtual DbSet<product_spec> product_spec { get; set; }
        public virtual DbSet<role> role { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<user> user { get; set; }
    }
}
