//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BurgerPlusUC.ApplicationDate
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_item
    {
        public int item_id { get; set; }
        public int order_id { get; set; }
        public int product_id { get; set; }
        public decimal quantity { get; set; }
        public decimal price { get; set; }
        public Nullable<decimal> subtotal { get; set; }
    
        public virtual customer_order customer_order { get; set; }
        public virtual product product { get; set; }
    }
}
